title: Aristotelis Koutsouridis
description: Academic website
url: "https://ariskoutsou.github.io"
baseurl: ""
repository: ariskoutsou/ariskoutsou.github.io
permalink: /blog/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block_line_numbers: false

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - package.json
  - package-lock.json
  - node_modules
  - README.md
